// Interface automatically generated by schemas-to-ts

import { Calc } from '../../../calc/content-types/calc/calc';
import { Calc_Plain } from '../../../calc/content-types/calc/calc';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface CarClassCalc {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    shortText?: string;
    calc?: { data: Calc };
    subtitle?: string;
    slug?: string;
    locale: string;
    localizations?: { data: CarClassCalc[] };
  };
}
export interface CarClassCalc_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  shortText?: string;
  calc?: Calc_Plain;
  subtitle?: string;
  slug?: string;
  locale: string;
  localizations?: CarClassCalc[];
}

export interface CarClassCalc_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  shortText?: string;
  calc?: number;
  subtitle?: string;
  slug?: string;
  locale: string;
  localizations?: CarClassCalc[];
}

export interface CarClassCalc_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  shortText?: string;
  calc?: AdminPanelRelationPropertyModification<Calc_Plain>;
  subtitle?: string;
  slug?: string;
  locale: string;
  localizations?: CarClassCalc[];
}
