// Interface automatically generated by schemas-to-ts

import { DefaultCard } from '../../../../components/cards/interfaces/DefaultCard';
import { DefaultCard_Plain } from '../../../../components/cards/interfaces/DefaultCard';
import { DefaultCard_NoRelations } from '../../../../components/cards/interfaces/DefaultCard';

export interface Faq {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    text?: string;
    question: DefaultCard[];
    slug?: string;
    locale: string;
    localizations?: { data: Faq[] };
  };
}
export interface Faq_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  question: DefaultCard_Plain[];
  slug?: string;
  locale: string;
  localizations?: Faq[];
}

export interface Faq_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  question: DefaultCard_NoRelations[];
  slug?: string;
  locale: string;
  localizations?: Faq[];
}

export interface Faq_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  question: DefaultCard_Plain[];
  slug?: string;
  locale: string;
  localizations?: Faq[];
}
