// Interface automatically generated by schemas-to-ts

export interface Email {
  value?: string;
}
export interface Email_Plain {
  value?: string;
}

export interface Email_NoRelations {
  value?: string;
}

