// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface MediaImage {
  logoImage?: { data: Media };
}
export interface MediaImage_Plain {
  logoImage?: Media;
}

export interface MediaImage_NoRelations {
  logoImage?: number;
}

