// Interface automatically generated by schemas-to-ts

export interface Phone {
  value?: string;
}
export interface Phone_Plain {
  value?: string;
}

export interface Phone_NoRelations {
  value?: string;
}

