// Interface automatically generated by schemas-to-ts

export interface Property {
  label?: string;
  text?: string;
  value?: number;
}
export interface Property_Plain {
  label?: string;
  text?: string;
  value?: number;
}

export interface Property_NoRelations {
  label?: string;
  text?: string;
  value?: number;
}

