// Interface automatically generated by schemas-to-ts

export interface Tag {
  title: string;
  slug?: any;
}
export interface Tag_Plain {
  title: string;
  slug?: any;
}

export interface Tag_NoRelations {
  title: string;
  slug?: any;
}

