// Interface automatically generated by schemas-to-ts

export interface Technology {
  title?: string;
  description?: string;
  color?: any;
  order?: number;
}
export interface Technology_Plain {
  title?: string;
  description?: string;
  color?: any;
  order?: number;
}

export interface Technology_NoRelations {
  title?: string;
  description?: string;
  color?: any;
  order?: number;
}

