// Interface automatically generated by schemas-to-ts

import { Property } from './Property';
import { Property_Plain } from './Property';
import { Property_NoRelations } from './Property';

export interface Variant {
  size?: string;
  thickness?: number;
  quanity_in_box?: number;
  sqrt?: number;
  weight?: number;
  specific_weight?: number;
  kmp?: number;
  adhesion?: number;
  temp?: string;
  property: Property[];
}
export interface Variant_Plain {
  size?: string;
  thickness?: number;
  quanity_in_box?: number;
  sqrt?: number;
  weight?: number;
  specific_weight?: number;
  kmp?: number;
  adhesion?: number;
  temp?: string;
  property: Property_Plain[];
}

export interface Variant_NoRelations {
  size?: string;
  thickness?: number;
  quanity_in_box?: number;
  sqrt?: number;
  weight?: number;
  specific_weight?: number;
  kmp?: number;
  adhesion?: number;
  temp?: string;
  property: Property_NoRelations[];
}

