// Interface automatically generated by schemas-to-ts

import { Phone } from '../../../../components/fields/interfaces/Phone';
import { Email } from '../../../../components/fields/interfaces/Email';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Phone_Plain } from '../../../../components/fields/interfaces/Phone';
import { Email_Plain } from '../../../../components/fields/interfaces/Email';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Phone_NoRelations } from '../../../../components/fields/interfaces/Phone';
import { Email_NoRelations } from '../../../../components/fields/interfaces/Email';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export interface BaseConfig {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    CompanyName?: string;
    phone: Phone[];
    email: Email[];
    address?: string;
    metadata?: Seo;
    locale: string;
    localizations?: { data: BaseConfig[] };
  };
}
export interface BaseConfig_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  CompanyName?: string;
  phone: Phone_Plain[];
  email: Email_Plain[];
  address?: string;
  metadata?: Seo_Plain;
  locale: string;
  localizations?: BaseConfig[];
}

export interface BaseConfig_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  CompanyName?: string;
  phone: Phone_NoRelations[];
  email: Email_NoRelations[];
  address?: string;
  metadata?: Seo_NoRelations;
  locale: string;
  localizations?: BaseConfig[];
}

export interface BaseConfig_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  CompanyName?: string;
  phone: Phone_Plain[];
  email: Email_Plain[];
  address?: string;
  metadata?: Seo_Plain;
  locale: string;
  localizations?: BaseConfig[];
}
