// Interface automatically generated by schemas-to-ts

import { User } from '../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../common/schemas-to-ts/User';

export interface MetaData {
  PublishDate: Date;
  Author?: { data: User };
}
export interface MetaData_Plain {
  PublishDate: Date;
  Author?: User_Plain;
}

export interface MetaData_NoRelations {
  PublishDate: Date;
  Author?: number;
}

