// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { MetaSocial } from '../../../../components/shared/interfaces/MetaSocial';
import { SectionComponent } from '../../../../components/layout/interfaces/SectionComponent';
import { Link } from '../../../../components/links/interfaces/Link';
import { Section } from '../../../section/content-types/section/section';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { MetaSocial_Plain } from '../../../../components/shared/interfaces/MetaSocial';
import { SectionComponent_Plain } from '../../../../components/layout/interfaces/SectionComponent';
import { Link_Plain } from '../../../../components/links/interfaces/Link';
import { Section_Plain } from '../../../section/content-types/section/section';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { MetaSocial_NoRelations } from '../../../../components/shared/interfaces/MetaSocial';
import { SectionComponent_NoRelations } from '../../../../components/layout/interfaces/SectionComponent';
import { Link_NoRelations } from '../../../../components/links/interfaces/Link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Page {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    seo?: Seo;
    social?: MetaSocial;
    Section: SectionComponent[];
    url?: string;
    title?: string;
    shortText?: string;
    content?: string;
    link: Link[];
    sections: { data: Section[] };
    slug?: string;
    locale: string;
    localizations?: { data: Page[] };
  };
}
export interface Page_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_Plain;
  social?: MetaSocial_Plain;
  Section: SectionComponent_Plain[];
  url?: string;
  title?: string;
  shortText?: string;
  content?: string;
  link: Link_Plain[];
  sections: Section_Plain[];
  slug?: string;
  locale: string;
  localizations?: Page[];
}

export interface Page_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_NoRelations;
  social?: MetaSocial_NoRelations;
  Section: SectionComponent_NoRelations[];
  url?: string;
  title?: string;
  shortText?: string;
  content?: string;
  link: Link_NoRelations[];
  sections: number[];
  slug?: string;
  locale: string;
  localizations?: Page[];
}

export interface Page_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  seo?: Seo_Plain;
  social?: MetaSocial_Plain;
  Section: SectionComponent_Plain[];
  url?: string;
  title?: string;
  shortText?: string;
  content?: string;
  link: Link_Plain[];
  sections: AdminPanelRelationPropertyModification<Section_Plain>;
  slug?: string;
  locale: string;
  localizations?: Page[];
}
