// Interface automatically generated by schemas-to-ts

export interface AboutUsPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    slug: string;
    Title: string;
    Description?: any;
    locale: string;
    localizations?: { data: AboutUsPage[] };
  };
}
export interface AboutUsPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug: string;
  Title: string;
  Description?: any;
  locale: string;
  localizations?: AboutUsPage[];
}

export interface AboutUsPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug: string;
  Title: string;
  Description?: any;
  locale: string;
  localizations?: AboutUsPage[];
}

export interface AboutUsPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  slug: string;
  Title: string;
  Description?: any;
  locale: string;
  localizations?: AboutUsPage[];
}
