// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Serie } from '../../../serie/content-types/serie/serie';
import { Section } from '../../../section/content-types/section/section';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Serie_Plain } from '../../../serie/content-types/serie/serie';
import { Section_Plain } from '../../../section/content-types/section/section';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Catalog {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    seo?: Seo;
    series: { data: Serie[] };
    sections: { data: Section[] };
    locale: string;
    localizations?: { data: Catalog[] };
  };
}
export interface Catalog_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  seo?: Seo_Plain;
  series: Serie_Plain[];
  sections: Section_Plain[];
  locale: string;
  localizations?: Catalog[];
}

export interface Catalog_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  seo?: Seo_NoRelations;
  series: number[];
  sections: number[];
  locale: string;
  localizations?: Catalog[];
}

export interface Catalog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  seo?: Seo_Plain;
  series: AdminPanelRelationPropertyModification<Serie_Plain>;
  sections: AdminPanelRelationPropertyModification<Section_Plain>;
  locale: string;
  localizations?: Catalog[];
}
