// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Link } from '../../../../components/links/interfaces/Link';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Link_Plain } from '../../../../components/links/interfaces/Link';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { Link_NoRelations } from '../../../../components/links/interfaces/Link';

export interface Global {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    defaultMetadata?: Seo;
    FooterMenu: Link[];
    HeaderMenu: Link[];
    locale: string;
    localizations?: { data: Global[] };
  };
}
export interface Global_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  defaultMetadata?: Seo_Plain;
  FooterMenu: Link_Plain[];
  HeaderMenu: Link_Plain[];
  locale: string;
  localizations?: Global[];
}

export interface Global_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  defaultMetadata?: Seo_NoRelations;
  FooterMenu: Link_NoRelations[];
  HeaderMenu: Link_NoRelations[];
  locale: string;
  localizations?: Global[];
}

export interface Global_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  defaultMetadata?: Seo_Plain;
  FooterMenu: Link_Plain[];
  HeaderMenu: Link_Plain[];
  locale: string;
  localizations?: Global[];
}
