// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { PostCategory } from '../../../post-category/content-types/post-category/post-category';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { PostCategory_Plain } from '../../../post-category/content-types/post-category/post-category';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Post {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    text?: string;
    shortText?: string;
    image?: { data: Media };
    seo?: Seo;
    post_category?: { data: PostCategory };
    slug?: string;
    locale: string;
    localizations?: { data: Post[] };
  };
}
export interface Post_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  text?: string;
  shortText?: string;
  image?: Media;
  seo?: Seo_Plain;
  post_category?: PostCategory_Plain;
  slug?: string;
  locale: string;
  localizations?: Post[];
}

export interface Post_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  text?: string;
  shortText?: string;
  image?: number;
  seo?: Seo_NoRelations;
  post_category?: number;
  slug?: string;
  locale: string;
  localizations?: Post[];
}

export interface Post_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  text?: string;
  shortText?: string;
  image?: AdminPanelRelationPropertyModification<Media>;
  seo?: Seo_Plain;
  post_category?: AdminPanelRelationPropertyModification<PostCategory_Plain>;
  slug?: string;
  locale: string;
  localizations?: Post[];
}
