// Interface automatically generated by schemas-to-ts

import { MediaImage } from '../../fields/interfaces/MediaImage';
import { MediaImage_Plain } from '../../fields/interfaces/MediaImage';
import { MediaImage_NoRelations } from '../../fields/interfaces/MediaImage';

export interface Footer {
  Logo?: MediaImage;
}
export interface Footer_Plain {
  Logo?: MediaImage_Plain;
}

export interface Footer_NoRelations {
  Logo?: MediaImage_NoRelations;
}

