// Interface automatically generated by schemas-to-ts

import { Title } from '../../fields/interfaces/Title';
import { Title_Plain } from '../../fields/interfaces/Title';
import { Title_NoRelations } from '../../fields/interfaces/Title';

export interface SectionComponent {
  BaseFields?: Title;
}
export interface SectionComponent_Plain {
  BaseFields?: Title_Plain;
}

export interface SectionComponent_NoRelations {
  BaseFields?: Title_NoRelations;
}

