// Interface automatically generated by schemas-to-ts

import { Section } from '../../../section/content-types/section/section';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Section_Plain } from '../../../section/content-types/section/section';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Calculator {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    shortText?: string;
    sections: { data: Section[] };
    seo?: Seo;
    locale: string;
    localizations?: { data: Calculator[] };
  };
}
export interface Calculator_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  shortText?: string;
  sections: Section_Plain[];
  seo?: Seo_Plain;
  locale: string;
  localizations?: Calculator[];
}

export interface Calculator_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  shortText?: string;
  sections: number[];
  seo?: Seo_NoRelations;
  locale: string;
  localizations?: Calculator[];
}

export interface Calculator_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  shortText?: string;
  sections: AdminPanelRelationPropertyModification<Section_Plain>;
  seo?: Seo_Plain;
  locale: string;
  localizations?: Calculator[];
}
