// Interface automatically generated by schemas-to-ts

export interface FormSubmission {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Name?: string;
    Email?: string;
    Phone?: string;
  };
}
export interface FormSubmission_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  Email?: string;
  Phone?: string;
}

export interface FormSubmission_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  Email?: string;
  Phone?: string;
}

export interface FormSubmission_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  Email?: string;
  Phone?: string;
}
