// Interface automatically generated by schemas-to-ts

export enum LinkType {
  Link = 'link',
  Outline = 'outline',
  ButtonPrimary = 'button-primary',
  DarkOutline = 'darkOutline',}

export interface Link {
  text: string;
  url: string;
  link_type?: LinkType;
}
export interface Link_Plain {
  text: string;
  url: string;
  link_type?: LinkType;
}

export interface Link_NoRelations {
  text: string;
  url: string;
  link_type?: LinkType;
}

