// Interface automatically generated by schemas-to-ts

import { Post } from '../../../post/content-types/post/post';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Post_Plain } from '../../../post/content-types/post/post';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface PostCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    posts: { data: Post[] };
    seo?: Seo;
    slug?: string;
    locale: string;
    localizations?: { data: PostCategory[] };
  };
}
export interface PostCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  posts: Post_Plain[];
  seo?: Seo_Plain;
  slug?: string;
  locale: string;
  localizations?: PostCategory[];
}

export interface PostCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  posts: number[];
  seo?: Seo_NoRelations;
  slug?: string;
  locale: string;
  localizations?: PostCategory[];
}

export interface PostCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  posts: AdminPanelRelationPropertyModification<Post_Plain>;
  seo?: Seo_Plain;
  slug?: string;
  locale: string;
  localizations?: PostCategory[];
}
