// Interface automatically generated by schemas-to-ts

import { Serie } from '../../../serie/content-types/serie/serie';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Variant } from '../../../../components/fields/interfaces/Variant';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { ProductCategory } from '../../../product-category/content-types/product-category/product-category';
import { Serie_Plain } from '../../../serie/content-types/serie/serie';
import { Variant_Plain } from '../../../../components/fields/interfaces/Variant';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { ProductCategory_Plain } from '../../../product-category/content-types/product-category/product-category';
import { Variant_NoRelations } from '../../../../components/fields/interfaces/Variant';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  VibrationIsolation = 'Виброизоляция:Vibration isolation.',
  Soundproofing = 'Шумоизоляция|Soundproofing',
  ThermoacousticInsulation = 'Теплозвукоизоляция|Thermoacoustic insulation.',
  SealantAndDecor = 'Уплотнитель и декор|Sealant and decor.',
  Accessories = 'Аксессуары|Accessories',
  VibroThermalNoiseInsulation = 'Вибро - тепло - шумоизоляция|Vibro-thermal-noise insulation.',}
export enum Class {
  Premium = 'Premium',
  Middle = 'Middle',
  Base = 'Base',}

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    series?: { data: Serie[] };
    type?: Type;
    place?: any;
    class?: Class;
    images?: { data: Media[] };
    description?: string;
    variants: Variant[];
    seo?: Seo;
    product_category?: { data: ProductCategory };
    slug?: string;
    locale: string;
    localizations?: { data: Product[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  series?: Serie_Plain[];
  type?: Type;
  place?: any;
  class?: Class;
  images?: Media[];
  description?: string;
  variants: Variant_Plain[];
  seo?: Seo_Plain;
  product_category?: ProductCategory_Plain;
  slug?: string;
  locale: string;
  localizations?: Product[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  series?: number[];
  type?: Type;
  place?: any;
  class?: Class;
  images?: number[];
  description?: string;
  variants: Variant_NoRelations[];
  seo?: Seo_NoRelations;
  product_category?: number;
  slug?: string;
  locale: string;
  localizations?: Product[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  series?: AdminPanelRelationPropertyModification<Serie_Plain>;
  type?: Type;
  place?: any;
  class?: Class;
  images?: AdminPanelRelationPropertyModification<Media>[];
  description?: string;
  variants: Variant_Plain[];
  seo?: Seo_Plain;
  product_category?: AdminPanelRelationPropertyModification<ProductCategory_Plain>;
  slug?: string;
  locale: string;
  localizations?: Product[];
}
