// Interface automatically generated by schemas-to-ts

import { Serie } from '../../../serie/content-types/serie/serie';
import { CalcResult } from '../../../../components/fields/interfaces/CalcResult';
import { CarClassCalc } from '../../../car-class-calc/content-types/car-class-calc/car-class-calc';
import { Serie_Plain } from '../../../serie/content-types/serie/serie';
import { CalcResult_Plain } from '../../../../components/fields/interfaces/CalcResult';
import { CarClassCalc_Plain } from '../../../car-class-calc/content-types/car-class-calc/car-class-calc';
import { CalcResult_NoRelations } from '../../../../components/fields/interfaces/CalcResult';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Calc {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    series?: { data: Serie };
    result: CalcResult[];
    car_class_calc?: { data: CarClassCalc };
    locale: string;
    localizations?: { data: Calc[] };
  };
}
export interface Calc_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  series?: Serie_Plain;
  result: CalcResult_Plain[];
  car_class_calc?: CarClassCalc_Plain;
  locale: string;
  localizations?: Calc[];
}

export interface Calc_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  series?: number;
  result: CalcResult_NoRelations[];
  car_class_calc?: number;
  locale: string;
  localizations?: Calc[];
}

export interface Calc_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  series?: AdminPanelRelationPropertyModification<Serie_Plain>;
  result: CalcResult_Plain[];
  car_class_calc?: AdminPanelRelationPropertyModification<CarClassCalc_Plain>;
  locale: string;
  localizations?: Calc[];
}
