// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { DefaultCard } from '../../../../components/cards/interfaces/DefaultCard';
import { Link } from '../../../../components/links/interfaces/Link';
import { Product } from '../../../product/content-types/product/product';
import { Post } from '../../../post/content-types/post/post';
import { Serie } from '../../../serie/content-types/serie/serie';
import { CarClassCalc } from '../../../car-class-calc/content-types/car-class-calc/car-class-calc';
import { DefaultCard_Plain } from '../../../../components/cards/interfaces/DefaultCard';
import { Link_Plain } from '../../../../components/links/interfaces/Link';
import { Product_Plain } from '../../../product/content-types/product/product';
import { Post_Plain } from '../../../post/content-types/post/post';
import { Serie_Plain } from '../../../serie/content-types/serie/serie';
import { CarClassCalc_Plain } from '../../../car-class-calc/content-types/car-class-calc/car-class-calc';
import { DefaultCard_NoRelations } from '../../../../components/cards/interfaces/DefaultCard';
import { Link_NoRelations } from '../../../../components/links/interfaces/Link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  Default = 'default',
  Screen = 'screen',
  News = 'news',
  Geography = 'geography',
  ProductCatalog = 'product-catalog',
  Products = 'products',
  About = 'about',
  Related = 'related',
  Reviews = 'reviews',
  FormQuestions = 'form_questions',
  CalcCarClass = 'calc_car_class',
  CalcSeries = 'calc_series',
  CalcResult = 'calc_result',
  ParternershipOne = 'parternership_one',
  ParternershipTwo = 'parternership_two',
  ParternershipForm = 'parternership_form',
  FormGetprice = 'form_getprice',
  FormReview = 'form_review',
  FormWriteUs = 'form_write_us',}

export interface Section {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    background?: { data: Media };
    shortText?: string;
    cards: DefaultCard[];
    Links: Link[];
    products: { data: Product[] };
    posts: { data: Post[] };
    type?: Type;
    series: { data: Serie[] };
    nextLink?: boolean;
    media?: { data: Media };
    link?: string;
    car_class_calcs: { data: CarClassCalc[] };
    locale: string;
    localizations?: { data: Section[] };
  };
}
export interface Section_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  background?: Media;
  shortText?: string;
  cards: DefaultCard_Plain[];
  Links: Link_Plain[];
  products: Product_Plain[];
  posts: Post_Plain[];
  type?: Type;
  series: Serie_Plain[];
  nextLink?: boolean;
  media?: Media;
  link?: string;
  car_class_calcs: CarClassCalc_Plain[];
  locale: string;
  localizations?: Section[];
}

export interface Section_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  background?: number;
  shortText?: string;
  cards: DefaultCard_NoRelations[];
  Links: Link_NoRelations[];
  products: number[];
  posts: number[];
  type?: Type;
  series: number[];
  nextLink?: boolean;
  media?: number;
  link?: string;
  car_class_calcs: number[];
  locale: string;
  localizations?: Section[];
}

export interface Section_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  background?: AdminPanelRelationPropertyModification<Media>;
  shortText?: string;
  cards: DefaultCard_Plain[];
  Links: Link_Plain[];
  products: AdminPanelRelationPropertyModification<Product_Plain>;
  posts: AdminPanelRelationPropertyModification<Post_Plain>;
  type?: Type;
  series: AdminPanelRelationPropertyModification<Serie_Plain>;
  nextLink?: boolean;
  media?: AdminPanelRelationPropertyModification<Media>;
  link?: string;
  car_class_calcs: AdminPanelRelationPropertyModification<CarClassCalc_Plain>;
  locale: string;
  localizations?: Section[];
}
